---
# tasks file for avinetworks.avisdk

- name: Checking if avisdk python library is present
  command: /usr/bin/python -c 'from avi.sdk.avi_api import ApiSession'
  delegate_to: localhost
  changed_when: false
  register: avisdk_present
